### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by edinsoncs** [uptechteam/klarna-node#3]

**Comment by LarsBuur** [comment]
It works for me - maybe you should add more details about you problem.

**Comment by edinsoncs** [comment]
I have the problem of 401 not authorized, copy the uid and password, I would need some guidance on how to get these credentials well. you want the problem is that

**Comment by edinsoncs** [comment]
401 Authorization Required
![image](https://user-images.githubusercontent.com/4240285/55082990-f6f9c980-50a2-11e9-918a-b7a9e054b42c.png)
